# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Advertencia.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(390, 133)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 40, 331, 61))
        self.widget.setStyleSheet("QWidget#widget{\n"
"    background-color: rgb(56, 56, 56);\n"
"    background-color: rgb(213, 213, 213);\n"
"\n"
"border-radius:20px;\n"
"    gridline-color: rgb(255, 255, 255);\n"
"    border-color: rgb(255, 255, 255);\n"
"border: 1px solid white;\n"
"}")
        self.widget.setObjectName("widget")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 31, 31))
        self.label_5.setStyleSheet("border-image: url(:/Iconos/advertencia.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(40, 20, 271, 31))
        self.label_3.setStyleSheet("font: 14pt \"Lucida Console\";\n"
"color:red\n"
";\n"
"font: 70 10pt \"Rockwell Extra Bold\";")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.cerrar_5 = QtWidgets.QPushButton(self.widget)
        self.cerrar_5.setGeometry(QtCore.QRect(290, 10, 31, 21))
        self.cerrar_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cerrar_5.setStyleSheet("QPushButton#cerrar_5{\n"
"\n"
"background-color: rgb(6, 6, 6);\n"
"border-radius:6px;\n"
"border: 1px solid black;\n"
"\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"}")
        self.cerrar_5.setObjectName("cerrar_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(90, -10, 141, 51))
        self.label_6.setStyleSheet("font: 14pt \"Lucida Console\";\n"
"color:gray\n"
";\n"
"font: 70 12pt \"Rockwell Extra Bold\";")
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cerrar_5.setText(_translate("Form", "x"))
        self.label_6.setText(_translate("Form", "ADVERTENCIA"))
import imagen


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
