# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DiseñoInicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1037, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 1001, 521))
        self.widget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color: rgb(16, 16, 16);\n"
"    background-color: rgb(6, 6, 6);\n"
"border-radius:20px;\n"
"}")
        self.widget.setObjectName("widget")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1001, 51))
        self.frame.setStyleSheet("QFrame#frame{\n"
"    background-color: rgb(6, 6, 6);\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.min = QtWidgets.QPushButton(self.frame)
        self.min.setGeometry(QtCore.QRect(900, 10, 41, 21))
        self.min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.min.setStyleSheet("QPushButton#min{\n"
"    background-color: rgb(208, 208, 208);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"border-radius:6px;\n"
"border: 1px solid black;\n"
"\n"
"\n"
"}")
        self.min.setObjectName("min")
        self.cerrar = QtWidgets.QPushButton(self.frame)
        self.cerrar.setGeometry(QtCore.QRect(950, 10, 41, 21))
        self.cerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cerrar.setStyleSheet("QPushButton#cerrar{\n"
"background-color: rgb(255, 0, 0);\n"
"border-radius:6px;\n"
"border: 1px solid black;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"\n"
"}")
        self.cerrar.setObjectName("cerrar")
        self.BEnviarFoto = QtWidgets.QPushButton(self.widget)
        self.BEnviarFoto.setGeometry(QtCore.QRect(440, 380, 151, 61))
        self.BEnviarFoto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BEnviarFoto.setStyleSheet("QPushButton#BEnviarFoto{\n"
"background-color: rgb(52, 107, 98);\n"
"background-color: rgb(57, 57, 57);\n"
"font: 87 10pt \"Arial Black\";\n"
"border-radius:15px;\n"
"font: 8pt \"Gill Sans Ultra Bold\";\n"
"color:white;\n"
"}")
        self.BEnviarFoto.setObjectName("BEnviarFoto")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(390, 320, 311, 20))
        self.label_2.setStyleSheet("font: 14pt \"Lucida Console\";\n"
"color:gray;\n"
"font: 90 20pt \"Rockwell Extra Bold\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(400, 120, 221, 211))
        self.label_3.setStyleSheet("border-image: url(:/icono youtube/Icono youtube.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.min.setText(_translate("MainWindow", "-"))
        self.cerrar.setText(_translate("MainWindow", "x"))
        self.BEnviarFoto.setText(_translate("MainWindow", "INICIAR"))
        self.label_2.setText(_translate("MainWindow", "CLASIFICADOR"))
import imagen


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
