# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ventana1(object):
    def setupUi(self, Ventana1):
        Ventana1.setObjectName("Ventana1")
        Ventana1.resize(1034, 560)
        self.centralwidget = QtWidgets.QWidget(Ventana1)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(10, 10, 1001, 521))
        self.widget_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.widget_2.setStyleSheet("QWidget#widget_2{\n"
"\n"
"background-color: rgb(6, 6, 6);\n"
"border-radius:20px;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.frame_2 = QtWidgets.QFrame(self.widget_2)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1001, 51))
        self.frame_2.setStyleSheet("QFrame#frame_2{\n"
"    background-color: rgb(6, 6, 6);\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.min_2 = QtWidgets.QPushButton(self.frame_2)
        self.min_2.setGeometry(QtCore.QRect(900, 10, 41, 21))
        self.min_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.min_2.setStyleSheet("QPushButton#min_2{\n"
"    background-color: rgb(208, 208, 208);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"border-radius:6px;\n"
"border: 1px solid black;\n"
"\n"
"\n"
"}")
        self.min_2.setObjectName("min_2")
        self.cerrar_2 = QtWidgets.QPushButton(self.frame_2)
        self.cerrar_2.setGeometry(QtCore.QRect(950, 10, 41, 21))
        self.cerrar_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cerrar_2.setStyleSheet("QPushButton#cerrar_2{\n"
"\n"
"background-color: rgb(255, 0, 0);\n"
"border-radius:6px;\n"
"border: 1px solid black;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"\n"
"}")
        self.cerrar_2.setObjectName("cerrar_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 41, 41))
        self.label_3.setStyleSheet("border-image: url(:/icono youtube/Icono youtube.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(70, 20, 181, 20))
        self.label_2.setStyleSheet("font: 14pt \"Lucida Console\";\n"
"color:gray\n"
";\n"
"font: 70 15pt \"Rockwell Extra Bold\";")
        self.label_2.setObjectName("label_2")
        self.BEnviarFoto = QtWidgets.QPushButton(self.widget_2)
        self.BEnviarFoto.setGeometry(QtCore.QRect(220, 370, 151, 61))
        self.BEnviarFoto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BEnviarFoto.setStyleSheet("QPushButton#BEnviarFoto{\n"
"background-color: rgb(52, 107, 98);\n"
"background-color: rgb(57, 57, 57);\n"
"font: 87 10pt \"Arial Black\";\n"
"border-radius:15px;\n"
"font: 8pt \"Gill Sans Ultra Bold\";\n"
"color:white;\n"
"}")
        self.BEnviarFoto.setObjectName("BEnviarFoto")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget_2)
        self.textBrowser.setGeometry(QtCore.QRect(190, 100, 221, 231))
        self.textBrowser.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(6, 6, 6);\n"
"font: 16pt \"Franklin Gothic Demi Cond\";")
        self.textBrowser.setObjectName("textBrowser")
        self.line = QtWidgets.QFrame(self.widget_2)
        self.line.setGeometry(QtCore.QRect(173, 110, 20, 211))
        self.line.setStyleSheet("background-color: rgb(6, 6, 6);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.widget_2)
        self.line_2.setGeometry(QtCore.QRect(410, 110, 20, 211))
        self.line_2.setStyleSheet("background-color: rgb(6, 6, 6);")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.widget_2)
        self.line_3.setGeometry(QtCore.QRect(240, 120, 118, 3))
        self.line_3.setStyleSheet("background-color: rgb(53, 53, 53);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.widget_2)
        self.line_4.setGeometry(QtCore.QRect(240, 310, 118, 3))
        self.line_4.setStyleSheet("background-color: rgb(53, 53, 53);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(466, 100, 281, 281))
        self.label.setObjectName("label")
        Ventana1.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Ventana1)
        self.statusbar.setObjectName("statusbar")
        Ventana1.setStatusBar(self.statusbar)

        self.retranslateUi(Ventana1)
        QtCore.QMetaObject.connectSlotsByName(Ventana1)

    def retranslateUi(self, Ventana1):
        _translate = QtCore.QCoreApplication.translate
        Ventana1.setWindowTitle(_translate("Ventana1", "MainWindow"))
        self.min_2.setText(_translate("Ventana1", "-"))
        self.cerrar_2.setText(_translate("Ventana1", "x"))
        self.label_2.setText(_translate("Ventana1", "CLASIFICADOR"))
        self.BEnviarFoto.setText(_translate("Ventana1", "SUBIR"))
        self.textBrowser.setHtml(_translate("Ventana1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Franklin Gothic Demi Cond\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Para usar el clasificador, primero debes subir un archivo .csv.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Sï no sabes cómo hacerlo, mira el siguiente tutorial: </p></body></html>"))
        self.label.setText(_translate("Ventana1", "TextLabel"))
import imagen


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ventana1 = QtWidgets.QMainWindow()
    ui = Ui_Ventana1()
    ui.setupUi(Ventana1)
    Ventana1.show()
    sys.exit(app.exec_())
