# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtCore import *
 


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1037, 589)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 1001, 521))
        self.widget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.widget.setStyleSheet("QWidget#widget{\n"
"\n"
"background-color: rgb(6, 6, 6);\n"
"border-radius:20px;\n"
"}")
        self.widget.setObjectName("widget")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1001, 51))
        self.frame.setStyleSheet("QFrame#frame{\n"
"    background-color: rgb(6, 6, 6);\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.min = QtWidgets.QPushButton(self.frame)
        self.min.setGeometry(QtCore.QRect(900, 10, 41, 21))
        self.min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.min.setStyleSheet("QPushButton#min{\n"
"    background-color: rgb(208, 208, 208);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"border-radius:6px;\n"
"border: 1px solid black;\n"
"\n"
"\n"
"}")
        self.min.setObjectName("min")
        self.cerrar = QtWidgets.QPushButton(self.frame)
        self.cerrar.setGeometry(QtCore.QRect(950, 10, 41, 21))
        self.cerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cerrar.setStyleSheet("QPushButton#cerrar{\n"
"\n"
"background-color: rgb(255, 0, 0);\n"
"border-radius:6px;\n"
"border: 1px solid black;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"\n"
"}")
        self.cerrar.setObjectName("cerrar")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 41, 41))
        self.label_3.setStyleSheet("\n"
"border-image: url(:/prefijoNuevo/Icono youtube.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(70, 20, 181, 20))
        self.label_2.setStyleSheet("font: 14pt \"Lucida Console\";\n"
"color:gray\n"
";\n"
"font: 70 15pt \"Rockwell Extra Bold\";")
        self.label_2.setObjectName("label_2")
        self.BEnviarFoto = QtWidgets.QPushButton(self.widget)
        self.BEnviarFoto.setGeometry(QtCore.QRect(220, 370, 151, 61))
        self.BEnviarFoto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BEnviarFoto.setStyleSheet("QPushButton#BEnviarFoto{\n"
"background-color: rgb(52, 107, 98);\n"
"background-color: rgb(57, 57, 57);\n"
"font: 87 10pt \"Arial Black\";\n"
"border-radius:15px;\n"
"font: 8pt \"Gill Sans Ultra Bold\";\n"
"color:white;\n"
"}")
        self.BEnviarFoto.setObjectName("BEnviarFoto")
